version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  app1:
    image: your-app1-image
    ports:
      - "8080:8080"

  app2:
    image: your-app2-image
    ports:
      - "8081:8081"